---
abstract: 'Various locking implementations supporting processes and threads'
author:
  - 'Mario E. Roy <marioeroy AT gmail DOT com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
  perl: '5.008001'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.008001'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.55_02, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mutex
no_index:
  directory:
    - t
    - inc
provides:
  Mutex:
    file: lib/Mutex.pm
    version: '1.011'
  Mutex::Channel:
    file: lib/Mutex/Channel.pm
    version: '1.011'
  Mutex::Flock:
    file: lib/Mutex/Flock.pm
    version: '1.011'
  Mutex::Util:
    file: lib/Mutex/Util.pm
    version: '1.011'
requires:
  Carp: '0'
  Errno: '0'
  Fcntl: '0'
  IO::Handle: '0'
  Socket: '0'
  base: '0'
  perl: '5.008001'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/marioroy/mutex-perl/issues
  homepage: https://github.com/marioroy/mutex-perl
  license: https://dev.perl.org/licenses/
  repository: https://github.com/marioroy/mutex-perl.git
version: '1.011'
